baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Hi!"
enableEmoji = true

[taxonomies]
  category = "categories"
  tag = "tags"

[markup.highlight]
  codeFences = true
  guessSyntax = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = true
  lineNumbersInTable = true
  noClasses = true
  style = "vs"
  tabWidth = 2

# RSS, categories and tags disabled for an easy start
# See configuration options for more details: 
# https://gohugo.io/getting-started/configuration/#toml-configuration
# disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]
